
package com.pcm.ws.jws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WsItfTask", targetNamespace = "http://impl.v1.ws.api.service.yxt.gooben.com/", wsdlLocation = "http://115.239.137.23:9501/ws/v1?wsdl")
public class WsItfTask_Service
    extends Service
{

    private final static URL WSITFTASK_WSDL_LOCATION;
    private final static WebServiceException WSITFTASK_EXCEPTION;
    private final static QName WSITFTASK_QNAME = new QName("http://impl.v1.ws.api.service.yxt.gooben.com/", "WsItfTask");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://115.239.137.23:9501/ws/v1?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSITFTASK_WSDL_LOCATION = url;
        WSITFTASK_EXCEPTION = e;
    }

    public WsItfTask_Service() {
        super(__getWsdlLocation(), WSITFTASK_QNAME);
    }

    public WsItfTask_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSITFTASK_QNAME, features);
    }

    public WsItfTask_Service(URL wsdlLocation) {
        super(wsdlLocation, WSITFTASK_QNAME);
    }

    public WsItfTask_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSITFTASK_QNAME, features);
    }

    public WsItfTask_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsItfTask_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WsItfTask
     */
    @WebEndpoint(name = "WsItfTaskImplPort")
    public WsItfTask getWsItfTaskImplPort() {
        return super.getPort(new QName("http://impl.v1.ws.api.service.yxt.gooben.com/", "WsItfTaskImplPort"), WsItfTask.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsItfTask
     */
    @WebEndpoint(name = "WsItfTaskImplPort")
    public WsItfTask getWsItfTaskImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.v1.ws.api.service.yxt.gooben.com/", "WsItfTaskImplPort"), WsItfTask.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSITFTASK_EXCEPTION!= null) {
            throw WSITFTASK_EXCEPTION;
        }
        return WSITFTASK_WSDL_LOCATION;
    }

}
