
package com.pcm.ws.jws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WsItfTask", targetNamespace = "http://v1.ws.api.service.yxt.gooben.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WsItfTask {


    /**
     * 
     * @param parameters
     * @param token
     * @return
     *     returns com.pcm.ws.jws.GetSentResultCallResponse
     */
    @WebMethod
    @WebResult(name = "getSentResultCallResponse", targetNamespace = "http://v1.ws.api.service.yxt.gooben.com/", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public GetSentResultCallResponse getSentResultCall(
        @WebParam(name = "getSentResultCall", targetNamespace = "http://v1.ws.api.service.yxt.gooben.com/", partName = "parameters")
        GetSentResultCall parameters,
        @WebParam(name = "token", targetNamespace = "http://v1.ws.api.service.yxt.gooben.com/", header = true, partName = "token")
        String token);

    /**
     * 
     * @param parameters
     * @param token
     * @return
     *     returns com.pcm.ws.jws.GetSubmitResultResponse
     */
    @WebMethod
    @WebResult(name = "getSubmitResultResponse", targetNamespace = "http://v1.ws.api.service.yxt.gooben.com/", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public GetSubmitResultResponse getSubmitResult(
        @WebParam(name = "getSubmitResult", targetNamespace = "http://v1.ws.api.service.yxt.gooben.com/", partName = "parameters")
        GetSubmitResult parameters,
        @WebParam(name = "token", targetNamespace = "http://v1.ws.api.service.yxt.gooben.com/", header = true, partName = "token")
        String token);

    /**
     * 
     * @param parameters
     * @param token
     * @return
     *     returns com.pcm.ws.jws.AddFileResponse
     */
    @WebMethod
    @WebResult(name = "addFileResponse", targetNamespace = "http://v1.ws.api.service.yxt.gooben.com/", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public AddFileResponse addFile(
        @WebParam(name = "addFile", targetNamespace = "http://v1.ws.api.service.yxt.gooben.com/", partName = "parameters")
        AddFile parameters,
        @WebParam(name = "token", targetNamespace = "http://v1.ws.api.service.yxt.gooben.com/", header = true, partName = "token")
        String token);

    /**
     * 
     * @param parameters
     * @param token
     * @return
     *     returns com.pcm.ws.jws.GetSentTaskResultCallResponse
     */
    @WebMethod
    @WebResult(name = "getSentTaskResultCallResponse", targetNamespace = "http://v1.ws.api.service.yxt.gooben.com/", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public GetSentTaskResultCallResponse getSentTaskResultCall(
        @WebParam(name = "getSentTaskResultCall", targetNamespace = "http://v1.ws.api.service.yxt.gooben.com/", partName = "parameters")
        GetSentTaskResultCall parameters,
        @WebParam(name = "token", targetNamespace = "http://v1.ws.api.service.yxt.gooben.com/", header = true, partName = "token")
        String token);

    /**
     * 
     * @param parameters
     * @param token
     * @return
     *     returns com.pcm.ws.jws.GetSentTaskResultSmsResponse
     */
    @WebMethod
    @WebResult(name = "getSentTaskResultSmsResponse", targetNamespace = "http://v1.ws.api.service.yxt.gooben.com/", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public GetSentTaskResultSmsResponse getSentTaskResultSms(
        @WebParam(name = "getSentTaskResultSms", targetNamespace = "http://v1.ws.api.service.yxt.gooben.com/", partName = "parameters")
        GetSentTaskResultSms parameters,
        @WebParam(name = "token", targetNamespace = "http://v1.ws.api.service.yxt.gooben.com/", header = true, partName = "token")
        String token);

    /**
     * 
     * @param parameters
     * @param token
     * @return
     *     returns com.pcm.ws.jws.SubmitTaskResponse
     */
    @WebMethod
    @WebResult(name = "submitTaskResponse", targetNamespace = "http://v1.ws.api.service.yxt.gooben.com/", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public SubmitTaskResponse submitTask(
        @WebParam(name = "submitTask", targetNamespace = "http://v1.ws.api.service.yxt.gooben.com/", partName = "parameters")
        SubmitTask parameters,
        @WebParam(name = "token", targetNamespace = "http://v1.ws.api.service.yxt.gooben.com/", header = true, partName = "token")
        String token);

    /**
     * 
     * @param parameters
     * @param token
     * @return
     *     returns com.pcm.ws.jws.GetSentResultSmsResponse
     */
    @WebMethod
    @WebResult(name = "getSentResultSmsResponse", targetNamespace = "http://v1.ws.api.service.yxt.gooben.com/", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public GetSentResultSmsResponse getSentResultSms(
        @WebParam(name = "getSentResultSms", targetNamespace = "http://v1.ws.api.service.yxt.gooben.com/", partName = "parameters")
        GetSentResultSms parameters,
        @WebParam(name = "token", targetNamespace = "http://v1.ws.api.service.yxt.gooben.com/", header = true, partName = "token")
        String token);

    /**
     * 
     * @param unixtick
     * @param password
     * @param userCode
     * @return
     *     returns com.pcm.ws.jws.InterfaceResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "authorization", targetNamespace = "http://v1.ws.api.service.yxt.gooben.com/", className = "com.pcm.ws.jws.Authorization")
    @ResponseWrapper(localName = "authorizationResponse", targetNamespace = "http://v1.ws.api.service.yxt.gooben.com/", className = "com.pcm.ws.jws.AuthorizationResponse")
    public InterfaceResult authorization(
        @WebParam(name = "userCode", targetNamespace = "")
        String userCode,
        @WebParam(name = "password", targetNamespace = "")
        String password,
        @WebParam(name = "unixtick", targetNamespace = "")
        long unixtick);

    /**
     * 
     * @param parameters
     * @param token
     * @return
     *     returns com.pcm.ws.jws.GetSmsReceiveResponse
     */
    @WebMethod
    @WebResult(name = "getSmsReceiveResponse", targetNamespace = "http://v1.ws.api.service.yxt.gooben.com/", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public GetSmsReceiveResponse getSmsReceive(
        @WebParam(name = "getSmsReceive", targetNamespace = "http://v1.ws.api.service.yxt.gooben.com/", partName = "parameters")
        GetSmsReceive parameters,
        @WebParam(name = "token", targetNamespace = "http://v1.ws.api.service.yxt.gooben.com/", header = true, partName = "token")
        String token);

}
